### ISSUE TITLE
How to make the inference samples sound more like the samples that the trainier logs to wandb?

### ISSUE THREAD

**Issue by BlakeOne** [Kinyugo/msanii#11]
Hello, I'm trying out the Masanii notebooks and was wondering how to get the quality of the samples created by the inference notebook to better match the ones that the training notebook logs to wandb? 🙏

Because it seems like the samples that lit_diffusion.py logs to wandb under the name "neural_vocoder" should be comparable to the samples created by the inference notebook but the ones created by the inference notebook are much noisier...

For example, assuming the default settings in the training notebook are used, how could the settings in the sampling section of the inference notebook be changed to create results more similar to those logged by the training notebook?

**Comment by Kinyugo** [comment]
Hello, I would require more info about the config and also see some logs to help determine what could be the issue.

**Comment by BlakeOne** [comment]
The configs are just the ones in the notebooks. It seems like inference must be generating the samples differently than training but I can't figure out what the difference is...

I tried using 200 for num_inference_steps and num_griffin_lim_iters. And it looks like training is using 20 steps and 100 iterations for the samples so I tried that too.

**Comment by Kinyugo** [comment]
I am not sure why there would be a difference in the inference.

**Comment by BlakeOne** [comment]
Oh well maybe I just got lucky with some of the logged samples then. I'll keep training and see how it goes - I'm only at about 6k for the vocoder and 15k for the unet so far, so lots of training steps left to go... Thanks! :)

**Comment by Kinyugo** [comment]
That might be the issue. Early on in the training the samples are very noisy, for the unet. The neural vocoder not so much but longer training helps as well. If your music data is complex, e.g: multiple instruments, I would recommend that you train longer.
